create database if not exists DB_ql_tts;
use DB_ql_tts;

-- DROP DATABASE DB_ql_tts;

CREATE TABLE IF NOT EXISTS USER(
	ID_USER INT auto_increment,
    TENDANGNHAP VARCHAR(30) NOT NULL,
    MATKHAU VARCHAR(30) NOT NULL,
	TEN NVARCHAR(30),
    EMAIL VARCHAR(30),
    SDT VARCHAR(15),
    
    primary key(ID_USER)
);

CREATE TABLE IF NOT EXISTS NHIEMVU(
	ID_NV INT auto_increment,
    ID_TTSTHUCHIEN INT NOT NULL,
    TENNV NVARCHAR(30) NOT NULL,
	MOTA NVARCHAR(255),
    NGAYTAO DATE,
    NGAYHOANTHANH DATE,
    TRANGTHAI INT,
    
    primary key(ID_NV)
);

CREATE TABLE IF NOT EXISTS THUCTAPSINH(
	ID_TTS INT auto_increment,
    TEN NVARCHAR(30) NOT NULL,
    SDT VARCHAR(15),
	CHUYENNGANH NVARCHAR(255) NOT NULL,
    SVNAM INT NOT NULL,
    CVFILE NVARCHAR(255),
    NGAYTHUCTAP DATE,
    NGAYKETTHUC DATE,
    KQTHUCTAP INT,
    
    primary key(ID_TTS)
);

CREATE TABLE IF NOT EXISTS BINHLUAN(
	ID_BINHLUAN INT auto_increment,
    ID_NHIEMVU INT,
    ID_USER INT,
	NOIDUNG NVARCHAR(255),
    
    primary key(ID_BINHLUAN,ID_NHIEMVU)
);

ALTER TABLE NHIEMVU
ADD CONSTRAINT FK_NHIEMVU_THUCTAPSINH
FOREIGN KEY (ID_TTSTHUCHIEN) REFERENCES THUCTAPSINH(ID_TTS);

ALTER TABLE BINHLUAN
ADD CONSTRAINT FK_BINHLUAN_NHIEMVU
FOREIGN KEY (ID_NHIEMVU) REFERENCES NHIEMVU(ID_NV);

ALTER TABLE BINHLUAN
ADD CONSTRAINT FK_BINHLUAN_USER
FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER);
