spring:


      
  datasource:
    url: jdbc:mysql://localhost:3306/DB_ql_tts
    username: root
    password: 12345

    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      
  jackson:
    serialization:
      fail-on-empty-beans: false
      
  flyway:
    enabled: true
    driver-class-name: org.mysql.Driver

server:
  port: 8080